---
layout: cv
title: Caleb Tubbs's CV
---
# Caleb Tubbs
Brigham Young University - Idaho Student

<div id="webaddress">
<a href="calebtubbs17@gmail.com">calebtubbs17@gmail.com</a>
</div>


## Currently

Attending Brigham Young University - Idaho
Computer Science Major Data Science Minor

### Specialized in

Programming in Python, Mysql, Javascript, R, Html, Css


### Research interests

Software engineering
Computer Science


## Education

`2022-Current`
__Brigham Young University-Idaho, Rexburg.__


## Awards

Eagle Scout

## Occupation

`2020`
__Helena Motors__, Helena, MT

- Porter
- Organized where cars would be placed in the parking lot and helped with cleaning and other responsibilities dealing with the customers. 

`2021-2022`
__Progrexion__, Rexburg, Id

- Sales agent
- Took phone calls from potential clients and turned the calls into sales.

`2023`
__Cedars Lodge__, Ketchikan, AK

- Fish Cutter
- Long hours of hard labor cutting fish for up to 14 hours a day. It made my work ethic and drive become much stronger

<!-- ### Footer

Last updated: January 2024 -->